# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
  push:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ clang libgtest-dev cmake

      - name: build gtest
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib
      - name: set compiler
        run: |
            if [ "${{ matrix.compiler }}" = "gcc" ]; then
              echo "CXX=g++" >> $GITHUB_ENV
            else
              echo "CXX=clang++" >> $GITHUB_ENV
            fi
      - name: build test
        run: $CXX -std=c++20 tests/test.cpp -lgtest -lpthread -Iinclude -o test

      - name: run test
        run: ./test --gtest_color=yes
