# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
  push:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'

jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: install vcpkg and dependencies
        uses: lukka/run-vcpkg@v11
        with:
          runVcpkgFormatString: |
            ["install"]
          vcpkgGitCommitId: ef7dbf94b9198bc58f45951adcf1f041fcbc5ea0
          runVcpkgInstall: true      


      - name: set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: build test
        run: |
          cl /std:c++20 /EHsc /Iinclude /I"D:/a/luco/luco/vcpkg/packages/gtest_x64-windows/include" /Fe:test.exe tests\test.cpp /link /LIBPATH:"D:/a/luco/luco/vcpkg/packages/gtest_x64-windows/lib" gtest.lib

